## Settings that can be changed to impact model outputs.

extract:
  stage1:
    descriptions: |
      :param header_bound: Number of points from top to keep (or skip) depending on logic.
      :param footer_bound: Number of points from bottom to keep (or skip).
      :param min_occurrences: Minimum times a piece of text must appear to be considered 'recurring'.
    header_bound: 100
    footer_bound: 100
    min_occurrences: 2
  coordinates:
    bounds:
      detect_header_footer_bounds:
        description: |
          Analyzes a PDF to detect consistent header and footer regions and returns their boundary positions.
          header_threshold: How many points from the top we consider "header"
          footer_threshold: How many points from the bottom we consider "footer"
          min_occurrence_ratio: Minimum ratio of pages that must contain the header/footer
        header_threshold: 50
        footer_threshold: 50
        min_occurrence_ratio: 0.5
