"""Make each inference request unique

Revision ID: 1b64f4c53c9d
Revises: b36f54ab3d32
Create Date: 2025-05-17 00:27:56.490119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1b64f4c53c9d'
down_revision: Union[str, None] = 'b36f54ab3d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llminferencetablestructure', sa.Column('run_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llminferencetablestructure', 'run_uuid')
    # ### end Alembic commands ###
