"""Fix typo in classification_label

Revision ID: b36f54ab3d32
Revises: 503669bd6884
Create Date: 2025-05-16 23:13:14.419818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b36f54ab3d32'
down_revision: Union[str, None] = '503669bd6884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llminferencetablestructure', sa.Column('classification_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('llminferencetablestructure', 'clasification_label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llminferencetablestructure', sa.Column('clasification_label', sa.VARCHAR(), nullable=False))
    op.drop_column('llminferencetablestructure', 'classification_label')
    # ### end Alembic commands ###
